config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"

  resources :lessons, only: %i(new create show edit update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  mount_uploader :document, DocumentUploader

  validates :name, :description, :document,
    :size, :page_count, :preview_pages, presence: true

  scope :newest, -> {order created_at: :desc, id: :desc}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :load_lesson, only: %i(show edit update)

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new lesson_params
    @success = @lesson.save
    if @success
      flash[:success] = "Create lesson success";
      redirect_to lesson_path(@lesson)
    end
  end

  def index
    @lessons = Lesson.newest.page(params[:page]).per Settings.lesson.per_page
  end

  def show
  end

  def edit
  end

  def update
    @success = @lesson.update lesson_params
    if @success
      flash[:success] = "Update lesson success";
      redirect_to lesson_path(@lesson)
    end
  end

  private

  def load_lesson
    @lesson = Lesson.find_by id: params[:id]
    return if @lesson

    flash[:danger] = "Lesson not found"
    redirect_to root_url
  end

  def lesson_params
    params.require(:lesson).permit :name, :description, :document
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoPdfJs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf.min.js" %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for lesson, remote: true, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
      <p class="text-danger js-error-lesson-name"></p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control", rows: 5 %>
      <p class="text-danger js-error-lesson-description"></p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.file_field :document, class: "form-control js-file-lesson-document" %>
      <p class="text-danger js-error-lesson-document"></p>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success pull-right" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <iframe src="<%= lesson.document.url %>" frameborder="0"
        class="iframe-lesson-document js-iframe-lesson-document">
      </iframe>
    </div>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<tr>
  <td><%= lesson_counter + 1 %></td>
  <td><%= lesson.name %></td>
  <td><%= lesson.description %></td>
  <td><%= lesson.document.identifier %></td>
  <td>
    <%= link_to "View", lesson_path(lesson), class: "btn btn-info btn-sm" %>
  </td>
</tr>

app/views/lessons/create.js.erb
<% %i(name description document).each do |attribute| %>
  var error = $('.js-error-lesson-<%= attribute %>');
  error.html('<%= j @lesson.errors.to_hash(true)[attribute]&.first %>');
<% end %>

app/views/lessons/edit.html.erb
<div class="container">
  <h2>Update Lesson</h2>

  <%= render "lessons/form", lesson: @lesson %>
</div>

app/views/lessons/index.html.erb
<div class="container">
  <h2>Lesson List</h2>

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Description</th>
        <th>Document</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "lessons/lesson", collection: @lessons %>
    </tbody>
  </table>

  <div class="row">
    <div class="col-sm-6">
      <p><%= page_entries_info @lessons %></p>
    </div>
    <div class="col-sm-6">
      <%= link_to "Create Lesson", new_lesson_path, class: "btn btn-success pull-right" %>
    </div>
  </div>

  <%= paginate @lessons, theme: "twitter-bootstrap-3" %>
</div>

app/views/lessons/new.html.erb
<div class="container">
  <h2>Create Lesson</h2>

  <%= render "lessons/form", lesson: @lesson %>
</div>

app/views/lessons/show.html.erb
<div class="container">
  <h2><%= @lesson.name %></h2>

  <table class="table">
    <tbody>
      <tr>
        <th>ID</th>
        <td><%= @lesson.id %></td>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= @lesson.name %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= @lesson.description %></td>
      </tr>
      <tr>
        <th>Document</th>
        <td class="text-center">
          <div class="col-sm-12">
            <canvas class="canvas-lesson-document js-canvas-fullview-pdf" data-url="<%= @lesson.document.url %>">
          </div>
          <div class="col-sm-12">
            <button class="btn btn-primary btn-pdf-page">Next page</button>
            <input type="text" class="form-control form-control-pdf-page" value="Trang 1">
            <button class="btn btn-primary btn-pdf-page">Previous page</button>
          </div>
        </td>
      </tr>
    </tbody>
  </table>

  <div>
    <%= link_to "Update Lesson", edit_lesson_path(@lesson), class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/lessons/update.js.erb
<% %i(name description document).each do |attribute| %>
  var error = $('.js-error-lesson-<%= attribute %>');
  error.html('<%= j @lesson.errors.to_hash(true)[attribute]&.first %>');
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p class="text-center"><%= message %></p>
  </div>
<% end %>